### ISSUE TITLE
Can't load the plugin inside IDE on Linux Version

### ISSUE THREAD

**Issue by KevinErath** [nathanhoad/godot_dialogue_manager#178] opened 2023-05-04 14:52 UTC
**Describe the bug**
I have a godot-Project which loads without issues on Windows, but when i open the project on Linux the Dialogue Manager can't be initialized.

**Affected version**

- Dialogue Manager version: 2.15.3 (also tested 2.15.5 from github-Repo)
- Godot version: 4.0.2 (also tested 4.0 and 4.0.1)

**To Reproduce**

Load a godot project which has dialogue manager as addon installed.

Following errors will be listed:
SCRIPT ERROR: Parse Error: Could not find type "DialogueResource" in the current scope.
          at: GDScript::reload (res://addons/dialogue_manager/dialogue_manager.gd:67)
SCRIPT ERROR: Parse Error: Could not find type "DialogueResource" in the current scope.
          at: GDScript::reload (res://addons/dialogue_manager/dialogue_manager.gd:140)
SCRIPT ERROR: Parse Error: Could not find type "DialogueResource" in the current scope.
          at: GDScript::reload (res://addons/dialogue_manager/dialogue_manager.gd:153)
SCRIPT ERROR: Parse Error: Could not find type "DialogueResource" in the current scope.
          at: GDScript::reload (res://addons/dialogue_manager/dialogue_manager.gd:165)
SCRIPT ERROR: Parse Error: Could not find type "DialogueResource" in the current scope.
          at: GDScript::reload (res://addons/dialogue_manager/dialogue_manager.gd:408)
SCRIPT ERROR: Parse Error: Could not find type "DialogueManagerParser" in the current scope.
          at: GDScript::reload (res://addons/dialogue_manager/dialogue_manager.gd:119)
SCRIPT ERROR: Parse Error: Identifier "DialogueManagerParser" not declared in the current scope.
          at: GDScript::reload (res://addons/dialogue_manager/dialogue_manager.gd:119)
SCRIPT ERROR: Parse Error: Could not find type "DialogueManagerParseResult" in the current scope.
          at: GDScript::reload (res://addons/dialogue_manager/dialogue_manager.gd:121)
SCRIPT ERROR: Parse Error: Could not find type "DialogueResource" in the current scope.
          at: GDScript::reload (res://addons/dialogue_manager/dialogue_manager.gd:131)
SCRIPT ERROR: Parse Error: Identifier "DialogueResource" not declared in the current scope.
          at: GDScript::reload (res://addons/dialogue_manager/dialogue_manager.gd:131)
SCRIPT ERROR: Parse Error: Identifier "DialogueManagerParser" not declared in the current scope.
          at: GDScript::reload (res://addons/dialogue_manager/dialogue_manager.gd:273)
ERROR: Script does not inherit from Node: res://addons/dialogue_manager/dialogue_manager.gd.
   at: _create_autoload (editor/editor_autoload_settings.cpp:423)
SCRIPT ERROR: Parse Error: Could not find type "DialogueResource" in the current scope.
SCRIPT ERROR: Parse Error: Could not find type "DialogueManagerParseResult" in the current scope.
          at: GDScript::reload (res://addons/dialogue_manager/plugin.gd:115)
SCRIPT ERROR: Parse Error: Could not find type "DialogueResource" in the current scope.
          at: GDScript::reload (res://addons/dialogue_manager/plugin.gd:83)

**Expected behavior**
Dialogue Manager can be used under linux

**Comment by Selenyhr** [comment] 2023-05-05 02:18
Hi! Fellow Linux user here :) I can't say I have experienced this issue, which seems pretty weird.

If I take the `DialogueResource` class as an example, it is defined using `class_name`. So it should be managed and loaded by Godot itself.

I tried the following steps to reproduce your issue. Everything was done on my Linux machine:
- starting a blank project
- installing Dialogue Manager using the AssetLib
- enabling Dialogue Manager in the "Project settings > Plugins" tab
- made a new .dialogue file (which contains the starter text Nathan wrote)
- ran the test dialogue file

The program ran fine, except for the [RegEx issue](https://github.com/godotengine/godot/issues/76174) that created a few error messages.

Can you also try these steps, see if it's something with the base addon, or your project copy that went wrong? :)

Was the project created on Windows and then copied onto the Linux machine? If so maybe there are differences within the `.godot` hidden folder, or something like this. It is mentioned in the [documentation](https://docs.godotengine.org/en/stable/tutorials/best_practices/version_control_systems.html#files-to-exclude-from-vcs) that this folder holds project cache data, so it may mess a few things up due to the architecture differences of the two OSes if it is copied.

**Comment by KevinErath** [comment] 2023-05-05 10:20
Thanks for your hints. It helped me hunting down the issue.

It can be reproduced as follows:

* Create a new project
* Install the Dialogue Manager Addon and enable it
* Save the project an exit godot
* Delete the .godot Folder
* Restart the IDE and you will see it won't work this time

As i was using git to exchange the project between the platforms the .godot folder was not copied over (as it is added to .gitignore)

Btw. if you save the project and restart/reload it within godot it works again, as the missing file is recreated. This behaviour is different on Windows. Maybe this is a godot issue?

E.g. the missing file is .godot/global_script_class_cache.cfg

**Comment by nathanhoad** [comment] 2023-05-05 12:42
I don't have access to a Linux install at the moment so I can't really check anything yet. I did see a similar issue with earlier builds of Godot 4 in Windows, though, but it seemed to go away.

**Comment by nathanhoad** [comment] 2023-05-06 12:54
I'm going to close this for now as it seems to be more an issue with Godot.

**Closed by nathanhoad** 2023-05-06 12:54 UTC
Labels: bug
