### ISSUE TITLE
Disable options, are able to be selected with mouse.

### ISSUE THREAD

**Issue by LostPython1192** [nathanhoad/godot_dialogue_manager#82] opened 2022-08-18 21:33 UTC
When I have an option, that shouldn't be selectable you are still able to select it with the mouse. You can't with the arrows or anyway else, but with the mouse, you are able to select any option no matter what.

`What would you like to do?
- Clean stove. (need spray bottle) [if player_dict.has_spray_bottle == false]
	You shouldn't be able to read this 
- Cancel => Stove`

if you press Clean stove (with the mouse) without the spray bottle, it will still go through.
I still want to display the disabled options though.

**Comment by nathanhoad** [comment] 2022-08-19 02:15
Duplicate of #83

**Closed by nathanhoad** 2022-08-19 02:15 UTC
Labels: duplicate
